---
- name: 'Install chrony'
  community.general.opkg:
    name: "{{ (chrony_server_nts | bool or chrony_client_nts | bool) | ternary('chrony-nts', 'chrony') }}"
    state: present

- name: 'Configure chrony'
  ansible.builtin.template:
    dest: "{{ item['dest'] }}"
    src: "{{ item['src'] }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - src: chrony.j2
      dest: '/etc/config/chrony'
    - src: chrony.conf.j2
      dest: '/etc/chrony/chrony.conf'
  loop_control:
    label: "{{ item['dest'] }}"
  notify: _chrony_restart

- name: 'Read /etc/group'
  ansible.builtin.slurp:
    src: '/etc/group'
  when: "chrony_extra_groups | count > 0"
  register: _etc_group

- name: 'Add chrony user to extra groups'
  ansible.builtin.lineinfile:
    path: '/etc/group'
    line: "{{ _etc_group.content | b64decode | split('\n') | select('match', item | regex_escape ~ ':') | first | regex_replace('(?<!:)$', ',') }}chrony"
    regexp: "^{{ item }}:x:([0-9]+):(.*)$"
    backrefs: true
    state: present
  loop: "{{ chrony_extra_groups }}"
  when: "(_etc_group.content | b64decode | split('\\n') | select('match', item | regex_escape ~ ':x:[0-9]+:.*\\\\bchrony\\\\b') | count) == 0"

- name: 'Disable and stop Busybox ntpd'
  ansible.builtin.service:
    name: sysntpd
    enabled: false
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'stopped') }}"

- name: 'Enable and start chrony'
  ansible.builtin.service:
    name: chronyd
    enabled: true
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'started') }}"
