---
- name: 'Install chrony'
  community.general.opkg:
    name: "{{ (chrony_server_nts | bool or chrony_client_nts | bool) | ansible.builtin.ternary('chrony-nts', 'chrony') }}"
    state: present

- name: 'Configure chrony'
  ansible.builtin.template:
    dest: "{{ item['dest'] }}"
    src: "{{ item['src'] }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - src: chrony.j2
      dest: '/etc/config/chrony'
    - src: chrony.conf.j2
      dest: '/etc/chrony/chrony.conf'
  loop_control:
    label: "{{ item['dest'] }}"
  notify: _chrony_restart

- name: 'Disable and stop Busybox ntpd'
  ansible.builtin.service:
    name: sysntpd
    enabled: false
    state: "{{ ansible_facts['is_chroot'] | ansible.builtin.ternary(omit, 'stopped') }}"

- name: 'Enable and start chrony'
  ansible.builtin.service:
    name: chronyd
    enabled: true
    state: "{{ ansible_facts['is_chroot'] | ansible.builtin.ternary(omit, 'started') }}"
